TextWordsSearch.App.Web/Pages/Error.cshtml.cs
//-----------------------------------------------------------------------
// <copyright file="Error.cshtml.cs" company="Demo Projects Workshop">
//     Copyright (c) Demo Projects Workshop. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

#pragma warning disable SA1600 // ElementsMustBeDocumented

namespace TextWordsSearch.App.Web.Pages;

using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    private readonly ILogger<ErrorModel> errorlogger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        this.errorlogger = logger;
    }

    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(this.RequestId);

    public void OnGet()
    {
        this.RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier;
    }
}

TextWordsSearch.App.Web/Pages/Index.cshtml.cs
//-----------------------------------------------------------------------
// <copyright file="Index.cshtml.cs" company="Demo Projects Workshop">
//     Copyright (c) Demo Projects Workshop. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------

#pragma warning disable SA1600 // ElementsMustBeDocumented

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TextWordsSearch.App.Web.Pages;

public class IndexModel : PageModel
{
    private readonly IWebHostEnvironment currentEnvironment;
    private readonly string uploadsFolderName;

    public IndexModel(IWebHostEnvironment environment)
    {
        this.currentEnvironment = environment;

        this.uploadsFolderName = Path.Combine(this.currentEnvironment.WebRootPath, "uploads");
        if (Directory.Exists(this.uploadsFolderName) is false)
        {
            Directory.CreateDirectory(this.uploadsFolderName);
        }
    }

    [BindProperty]
    public IFormFile? Upload { get; set; }

    public void OnGet()
    {
        this.ViewData["Title"] = "TextWordsSearchTool";
    }

    public async Task<IActionResult> OnPostUploadTextFileAsync()
    {
        if (this.Upload is not null)
        {
            string uploadFilePath = Path.Combine(this.uploadsFolderName, this.Upload.FileName);

            using (FileStream fileStream = new (uploadFilePath, FileMode.Create))
            {
                await this.Upload.CopyToAsync(fileStream);
            }

            if (System.IO.File.Exists(uploadFilePath))
            {
                DataStore.Create(uploadFilePath);
            }

            return this.RedirectToPage("/textcontent");
        }
        else
        {
            return this.RedirectToPage("/error");
        }
    }
}

TextWordsSearch.App.Web/Pages/Index.cshtml
@page
@model IndexModel
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<div class="container text-center">
    <h1 class="display-2">Welcome to the @ViewData["Title"]!</h1>
    <hr>
    <form asp-page-handler="UploadTextFile" method="POST" enctype="multipart/form-data">
        <div class="input-group mb-3">
            <input asp-for="Upload" type="file" class="form-control"/>
            <label class="input-group-text">Upload a Local Text File</label>
        </div>
        <br>
        <div class="row">
            <input type="submit" class="btn btn-primary" value="Read the Uploaded File">
        </div>
    </form>
    <hr>
</div>

TextWordsSearch.App.Web/Pages/MaxResult.cshtml
@page "/maxresult"

<div class="container text-center">
    <h2 class="display-4">Explore Results of Parsing the Text Content</h2>
    <hr>
    <div class="row">
        <a class="btn btn-primary" href="/textcontent">Return to the Text Content Page</a>
    </div>
</div>
<hr>
<div class="container text-center">
    <h4 class="display-5">Maximum Entry Count of Text Words:</h4>
    <br>
    <h4 class="display-2">@DataStore.MaximumWordsCountInfo.Key</h4>
</div>
<hr>
<div class="container text-center">
    <h4 class="display-6">Look at the Text Words List Ordered By Descending:</h4>
    <br>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col" style="color: white; background-color: black;">Count</th>
                <th scope="col" style="color: white; background-color: black;">Text Word</th>
            </tr>
        </thead>
        <tbody>
            @foreach (KeyValuePair<uint, List<string>> textWordInfo in @DataStore.WordsOrderedByDescending)
            {
                @foreach (string word in @textWordInfo.Value)
                {
                    <tr>
                        @if (@textWordInfo.Key == @DataStore.MaximumWordsCountInfo.Key)
                        {
                            <td style="background-color: lightgreen;">@textWordInfo.Key</td>
                            <td style="background-color: lightgreen;">@word</td>
                        }
                        else if (@textWordInfo.Key == @DataStore.MinimumWordsCountInfo.Key)
                        {
                            <td style="background-color: lightcoral;">@textWordInfo.Key</td>
                            <td style="background-color: lightcoral;">@word</td>
                        }
                        else
                        {
                            <td style="background-color: gray;">@textWordInfo.Key</td>
                            <td style="background-color: gray;">@word</td>
                        }
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<hr>
<div class="row">
    <a class="btn btn-primary" href="/textcontent">Return to the Text Content Page</a>
</div>

TextWordsSearch.App.Web/Pages/MinResult.cshtml
@page "/minresult"

<div class="container text-center">
    <h2 class="display-4">Explore Results of Parsing the Text Content</h2>
    <hr>
    <div class="row">
        <a class="btn btn-primary" href="/textcontent">Return to the Text Content Page</a>
    </div>
</div>
<hr>
<div class="container text-center">
    <h4 class="display-6">Minimum Entry Count of Text Words:</h4>
    <br>
    <h4 class="display-3">@DataStore.MinimumWordsCountInfo.Key</h4>
</div>
<hr>
<div class="container text-center">
    <h4 class="display-6">Look at the Text Words List Ordered By Ascending:</h4>
    <br>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col" style="color: white; background-color: black;">Count</th>
                <th scope="col" style="color: white; background-color: black;">Text Word</th>
            </tr>
        </thead>
        <tbody>
            @foreach (KeyValuePair<uint, List<string>> textWordInfo in @DataStore.WordsOrderedByAscending)
            {
                @foreach (string word in @textWordInfo.Value)
                {
                    <tr>
                        @if (@textWordInfo.Key == @DataStore.MinimumWordsCountInfo.Key)
                        {
                            <td style="background-color: lightgreen;">@textWordInfo.Key</td>
                            <td style="background-color: lightgreen;">@word</td>
                        }
                        else if (@textWordInfo.Key == @DataStore.MaximumWordsCountInfo.Key)
                        {
                            <td style="background-color: lightcoral;">@textWordInfo.Key</td>
                            <td style="background-color: lightcoral;">@word</td>
                        }
                        else
                        {
                            <td style="background-color: gray;">@textWordInfo.Key</td>
                            <td style="background-color: gray;">@word</td>
                        }
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
<hr>
<div class="row">
    <a class="btn btn-primary" href="/textcontent">Return to the Text Content Page</a>
</div>

TextWordsSearch.App.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TextWordsSearch.App.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TextWordsSearch.App.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Text Words Search Tool
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TextWordsSearch.App.Web/Pages/TextContent.cshtml
@page "/textcontent"
<div class="container text-center">
    <h2 class="display-4">Explore Content from the Uploaded Text File</h2>
    <hr>
    <div class="row">
        <div class="col-sm-6">
            <div style="row">
                <form action="/maxresult" method="GET">
                    <button class="btn btn-primary" >Show Words with the Maximum Count in the Content</button>
                </form>
            </div>
        </div>
        <div class="col-sm-6">
            <div style="row">
                <form action="/minresult" method="GET">
                    <button class="btn btn-primary">Show Words with the Minimum Count in the Content</button>
                </form>
            </div>

        </div>
    </div>
    <hr>
    <div class="row">
        <a class="btn btn-primary" href="/">Return to the Home Page</a>
    </div>
</div>
<hr>
<div class="container">
@for(int @index = 0; @index < @DataStore.CurrentInstance?.ContentStringsFromTextFile.Length; @index++)
{
    <div class="row">
        <div class="col-sm-1 text-center">
            <h6>@index</h6>
        </div>
        <div class="col-sm-11 text-left">
            <p>@DataStore.CurrentInstance?.ContentStringsFromTextFile[@index]</p>
        </div>
    </div>
}
</div>
<hr>
<div class="row">
    <a class="btn btn-primary" href="/">Return to the Home Page</a>
</div>